apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9000
  selector:
    app: helloworld
